const INTENT_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING_MANAGER_APPROVAL: 'PENDING_MANAGER_APPROVAL',
  REJECTED_BY_MANAGER: 'REJECTED_BY_MANAGER',
  PENDING_QUOTATION: 'PENDING_QUOTATION',
  QUOTATION_COLLECTED: 'QUOTATION_COLLECTED',
  PENDING_PO: 'PENDING_PO',
  SAMPLE_PO_CREATED: 'SAMPLE_PO_CREATED',
  PENDING_ADMIN_APPROVAL: 'PENDING_ADMIN_APPROVAL',
  REJECTED_BY_ADMIN: 'REJECTED_BY_ADMIN',
  PO_APPROVED: 'PO_APPROVED',
  PO_SENT: 'PO_SENT',
  DELIVERY_PENDING: 'DELIVERY_PENDING',
  PARTIAL_DELIVERY: 'PARTIAL_DELIVERY',
  FULL_DELIVERY: 'FULL_DELIVERY',
  INVOICE_UPLOADED: 'INVOICE_UPLOADED',
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_COMPLETED: 'PAYMENT_COMPLETED',
  CLOSED: 'CLOSED',
};

const ROLES = {
  USER: 'USER',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
  STORE_MANAGER: 'STORE_MANAGER',
};

const PRIORITY_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

const PO_STATUSES = {
  DRAFT: 'DRAFT',
  SAMPLE: 'SAMPLE',
  APPROVED: 'APPROVED',
  SENT: 'SENT',
  CONFIRMED: 'CONFIRMED',
  OPEN: 'OPEN',
  PARTIALLY_RECEIVED: 'PARTIALLY_RECEIVED',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
  CANCELLED: 'CANCELLED',
};

const INVOICE_STATUSES = {
  PENDING: 'PENDING',
  UPLOADED: 'UPLOADED',
  VERIFIED: 'VERIFIED',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PAID: 'PAID',
};

const DELIVERY_STATUSES = {
  PENDING: 'PENDING',
  IN_TRANSIT: 'IN_TRANSIT',
  PARTIAL: 'PARTIAL',
  COMPLETED: 'COMPLETED',
  RETURNED: 'RETURNED',
};

const ALLOWED_FILE_TYPES = {
  images: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'],
  documents: [
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.ms-excel',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ],
};

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10MB

module.exports = {
  INTENT_STATUSES,
  ROLES,
  PRIORITY_LEVELS,
  PO_STATUSES,
  INVOICE_STATUSES,
  DELIVERY_STATUSES,
  ALLOWED_FILE_TYPES,
  MAX_FILE_SIZE,
};
